# Solution using Personal Access Token (PAT)
name: Dependabot Security Check with PAT

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check Dependabot Alerts
        uses: Posture-Cybersecurity/dependabot-security-checker@main
        with:
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}  # Use PAT instead of GITHUB_TOKEN
          severities: 'critical,high,medium,low'
          output-file: 'security-report.csv'
          fail-on-alerts: 'false'  # Set to true for production
          
      - name: Display results
        run: |
          echo "=== Security Check Results ==="
          if [ -f security-report.csv ]; then
            echo "âœ… Security report generated successfully"
            echo "ðŸ“Š Report size: $(wc -l < security-report.csv) lines"
            echo ""
            echo "ðŸ“‹ Summary section:"
            grep -A 10 "# SUMMARY STATISTICS" security-report.csv || echo "No summary found"
          else
            echo "â„¹ï¸  No security report generated (no alerts found)"
          fi
          
      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-report-${{ github.run_number }}
          path: security-report.csv
          if-no-files-found: ignore
