# Example workflow to test the action in another repository
# Copy this to any repository you want to test with

name: Test Dependabot Security Checker

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]

jobs:
  test-security-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test Dependabot Security Checker
        uses: Posture-Cybersecurity/dependabot-security-checker@main  # Use main branch for testing
        with:
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}
          severities: 'critical,high,medium,low'
          output-file: 'security-test-report.csv'
          fail-on-alerts: 'false'  # Don't fail during testing
          
      - name: Show results
        run: |
          echo "=== Security Check Results ==="
          if [ -f security-test-report.csv ]; then
            echo "ðŸ“Š Report generated successfully"
            echo "ðŸ“ˆ Total lines: $(wc -l < security-test-report.csv)"
            echo ""
            echo "ðŸ“‹ Summary section:"
            grep -A 20 "# SUMMARY STATISTICS" security-test-report.csv || echo "No summary found"
          else
            echo "â„¹ï¸  No security report generated"
          fi
          
      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-test-report.csv
          if-no-files-found: ignore
