# Test different ways to reference your action
name: Test Action Versions

on:
  workflow_dispatch:

jobs:
  test-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test with main branch (latest)
        uses: Posture-Cybersecurity/dependabot-security-checker@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          severities: 'critical,high'
          output-file: 'test-main.csv'
          fail-on-alerts: 'false'
          
      - name: Test with specific version (after you create v1.0.0)
        uses: Posture-Cybersecurity/dependabot-security-checker@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          severities: 'critical,high'
          output-file: 'test-v1.csv'
          fail-on-alerts: 'false'
          
      - name: Compare results
        run: |
          echo "=== Version Comparison ==="
          echo "Main branch results:"
          if [ -f test-main.csv ]; then
            echo "✅ Main branch worked"
            wc -l test-main.csv
          else
            echo "❌ Main branch failed"
          fi
          
          echo ""
          echo "v1.0.0 results:"
          if [ -f test-v1.csv ]; then
            echo "✅ v1.0.0 worked"
            wc -l test-v1.csv
          else
            echo "❌ v1.0.0 failed"
          fi
